## OVERALL DESCRIPTION
## The functions allow to store in cache the inverse of a given matrix,
## once it is calculated, so it may be used again.

## Function makeCacheMatrix creates an object for matrix given
## as the function argument. The object is a list of four methods:
## 1. set       - changes the matrix to the given argument
##              and nullifies cached inverse
## 2. get       - returns the matrix
## 3. setinv    - stores the given argument as a cached inverse
## 4. getinv    - returns the value stored as a cached inverse
## Some basic checks of the input are performed.

makeCacheMatrix <- function(x = matrix())
{
    # check argument class
    if  (!is.matrix(x))
        stop("argument should be a matrix")
    # initialized object should have empty cache for inverse
    x_1     <- NULL
    # methods definitions
    set     <- function(y)
    {
        if  (!is.matrix(y))
            stop("argument should be a matrix")
        x       <<- y
        x_1     <<- NULL
    }
    get     <- function()
        x
    setinv  <- function(y)
    {
        if  (!is.matrix(y))
            stop("argument should be a matrix")
        x_1     <<- y
        NULL
    }
    getinv  <- function()
        x_1
    # function return:
    list( get    = get
        , getinv = getinv
        , set    = set
        , setinv = setinv
        )
}


## Function cacheSolve returns a matrix that is the inverse of 'x',
## first checking cache of the object, and if it is empty, calculating it
## using solve function.
## Some basic checks of the input are performed.

cacheSolve <-
    function(x, ...) {
        # check the function argument
        x_ok    <- FALSE
        if  (all(is.list(x), length(names(x)) > 0))
            if  (all(mapply(identical, names(x), c("get", "getinv", "set", "setinv"))))
                if  (all(sapply(c(x$get, x$getinv, x$set, x$setinv), is.function)))
                    x_ok <- TRUE
        if (!x_ok)
            stop("argument should be a list generated by makeCacheMatrix function")
        # check the cache of 'x'
        y       <- x$getinv()
        if (!is.null(y)) {
            message("getting cached data")
            return(y)
        }
        # following code is evaluated only if the cache is empty
        matrix  <- x$get()
        y       <- solve(matrix, ...)
        # store in cache the result
        x$setinv(y)
        # function return:
        y
    }
